version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/buildkite"
      - "/gitea"
      - "/matterbridge"
      - "/stronk"
      - "/web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directories:
      - "/stronk"
    schedule:
      interval: "weekly"
