# fly.toml file generated for lineageos-stronk on 2023-02-24T19:02:39-08:00

app = "lineageos-stronk"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true
[mounts]
source="stronk_data"
destination="/data"
