# fly.toml app configuration file generated for lineageos-buildkite on 2023-12-31T23:28:39-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lineageos-buildkite"
primary_region = "sea"

[env]
  BUILDKITE_AGENT_NAME = "fly-%hostname"
  BUILDKITE_HOOKS_PATH = "/hooks"

[processes]
  fly = "start --tags=\"queue=fly\""
