# fly.toml file generated for lineageos-matterbridge on 2021-11-30T17:24:50-08:00

app = "lineageos-matterbridge"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
IRC_NICK="lineagebot"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

