name: Deploy to app01
on:
  push:
    branches:
      - main
    paths:
      - 'gitea/**'
jobs:
  deploy:
    name: Deploy gitea
    runs-on: ubuntu-latest
    steps:
      - uses: lineageos-infra/app01-deploy@main
        with:
          api_key: ${{ secrets.APP01_API_KEY }}
          app: gitea
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: ${{ always() }}
    steps:
      - uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
