name: Deploy to Fly
on:
  push:
    branches:
      - main
    paths:
      - 'grafana/**'
jobs:
  deploy:
    name: Deploy grafana
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step runs `flyctl deploy`.
      - uses: superfly/flyctl-actions@master
        working-directory: ./grafana
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
