name: Deploy to app01
on:
  push:
    branches:
      - main
    paths:
      - 'matterbridge/**'
jobs:
  deploy:
    name: Deploy matterbridge
    runs-on: ubuntu-latest
    steps:
      - run: curl -H X-Api-Key:${{ secrets.APP01_API_KEY }} https://app01.lineageos.org/deploy/matterbridge/${{ github.sha }}
