name: Deploy to Fly
on:
  push:
    branches:
      - main
    paths:
      - 'matterbridge/**'
jobs:
  deploy:
    name: Deploy matterbridge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy
        working-directory: ./matterbridge
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only
