name: Deploy to Fly
on:
  push:
    branches:
      - main
    paths:
      - 'redis/**'
jobs:
  deploy:
    name: Deploy redis
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - name: deploy
        working-directory: ./redis
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          curl -L https://fly.io/install.sh | FLYCTL_INSTALL=/usr/local sh
          flyctl deploy
